In [25]:
# import library pandas
# syntax for imprt (import Library_name as pd)
import pandas as pd

In [26]:
data = pd.read_excel(
    "Customer Demographic Data Analysis Data.xlsx"
)

understanding dataset

Reading data

In [27]:
data.head()

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
0,CUS00005,2025-01-20 00:00:00,Male,49.0,Mogadishu,Healthcare,1024.44
1,CUS00034,NaN,Male,39.0,Baidoa,Teacher,827.25
2,CUS00176,2026-05-31 00:00:00,Male,NaN,Hargeisa,Teacher,661.3
3,CUS00026,2025-10-24 00:00:00,Female,20.0,Mogadishu,Student,295.45
4,CUS00195,2025-12-15 00:00:00,Male,31.0,Bosaso,Self-Employed,481.99

In [30]:
data.tail()

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
295,CUS00080,2025-03-29 00:00:00,Female,32.0,Mogadishu,self-employed,1235.89
296,CUS00145,2026-04-24 00:00:00,Female,57.0,Kismayo,Business Owner,749.33
297,CUS00049,2025-04-10 00:00:00,Female,33.0,Garowe,Civil Servant,661.71
298,CUS00035,2025-12-31 00:00:00,Female,41.0,Baidoa,Self-Employed,455.83
299,CUS00097,2025-04-03 00:00:00,Male,49.0,Bosaso,Student,NaN

In [31]:
data.sample(5)

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
249,CUS00089,2025-11-02 00:00:00,Female,40.0,Bosaso,Self-Employed,463.46
215,CUS00272,2025-06-24 00:00:00,Female,39.0,Kismayo,NaN,838.84
119,NaN,2026-05-09 00:00:00,Female,50.0,Mogadishu,Self-Employed,917.25
271,CUS00192,2026-05-26 00:00:00,Male,NaN,Hargeisa,Student,149.24
105,CUS00142,2026-04-12 00:00:00,Male,24.0,Mogadishu,Engineer,1411.64

#show the display data shape

In [32]:
data.shape

(300, 7)

this dataset 300 raws and 9 column

In [33]:
data.columns

Index(['Customer_ID', 'Registration_Date', 'Gender', 'Age', 'City',
       'Occupation', 'Monthly_Income'],
      dtype='object')

Display the datatype of my dataset using property

In [34]:
data.dtypes

Customer_ID           object
Registration_Date     object
Gender                object
Age                  float64
City                  object
Occupation            object
Monthly_Income        object
dtype: object

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        285 non-null    object
 1   Registration_Date  281 non-null    object
 2   Gender             283 non-null    object
 3   Age                284 non-null    float64
 4   City               284 non-null    object
 5   Occupation         285 non-null    object
 6   Monthly_Income     282 non-null    object
dtypes: float64(1), object(6)
memory usage: 16.5+ KB

display the describe

In [36]:
data.describe(include="all")

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
count,285,281,283,284.000000,284,285,282.00
unique,277,226,4,NaN,8,12,274.00
top,CUS00224,2026-05-15 00:00:00,Female,NaN,Mogadishu,Business Owner,1075.09
freq,2,4,147,NaN,112,50,2.00
mean,NaN,NaN,NaN,44.154930,NaN,NaN,NaN
std,NaN,NaN,NaN,16.125303,NaN,NaN,NaN
min,NaN,NaN,NaN,18.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,32.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,43.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,57.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,123.000000,NaN,NaN,NaN